# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rust/service_extensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rust/service_extensions.proto',
  package='rust',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1drust/service_extensions.proto\x12\x04rust\x1a google/protobuf/descriptor.proto:F\n\x1bservice_default_deadline_ms\x12\x1f.google.protobuf.ServiceOptions\x18\xd2\x86\x03 \x01(\x05:D\n\x1amethod_default_deadline_ms\x12\x1e.google.protobuf.MethodOptions\x18\xd3\x86\x03 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


SERVICE_DEFAULT_DEADLINE_MS_FIELD_NUMBER = 50002
service_default_deadline_ms = _descriptor.FieldDescriptor(
  name='service_default_deadline_ms', full_name='rust.service_default_deadline_ms', index=0,
  number=50002, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
METHOD_DEFAULT_DEADLINE_MS_FIELD_NUMBER = 50003
method_default_deadline_ms = _descriptor.FieldDescriptor(
  name='method_default_deadline_ms', full_name='rust.method_default_deadline_ms', index=1,
  number=50003, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['service_default_deadline_ms'] = service_default_deadline_ms
DESCRIPTOR.extensions_by_name['method_default_deadline_ms'] = method_default_deadline_ms
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(service_default_deadline_ms)
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(method_default_deadline_ms)

# @@protoc_insertion_point(module_scope)
