# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)


service_default_deadline_ms = ... # type: google___protobuf___descriptor___FieldDescriptor

method_default_deadline_ms = ... # type: google___protobuf___descriptor___FieldDescriptor
