[package]
name = "examples_gen"
version = "0.1.0"
authors = ["Parker Timmerman <parkertimmerman@dropbox.com>"]
edition = "2018"
publish = false

[dependencies]
#pb-jelly-gen = "0.0.17"  # If copying this example - use this
pb-jelly-gen = { path = "../../pb-jelly-gen" }
